name: Test Orders Monitor

on:
  workflow_dispatch:

jobs:
  test-orders-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Call Orders Monitor action
        uses: ./actions/orders-monitor
        with:
          url: 'https://httpbin.org/post'
          api_key: 'test-token-123'
          items: '1,2,3'
